apiVersion: v1
kind: Service
metadata:
  name: {{ include "kabisa-fleet.fullname" . }}-service
  labels:
    {{- include "kabisa-fleet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kabisa-fleet.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
